### PR TITLE
Add support to lint absolute URLs in blog posts

### PR DESCRIPTION
**Pull request by bdemers**
Broken up into two commits, one to add the lint rule, and one to fix the errors:

- detect absolute blog post URLs when linting: 303eceb6f973a8cbcc32f43931efa7d69846e966
- remove absolute urls to other blog posts

### CODE REVIEW

**Review by mraible — APPROVED** [review]
Trusting you on this one.

**Comment by mraible** [comment]
I discovered an issue with this today. If you're writing a post for another blog (e.g., the Auth0 blog), you don't want the links to be relative. However, CI fails because they are. Maybe we should update the logic to see if there's a `canonical` key in the front matter and allow absolute URLs if there are. Or maybe it's OK for the build to fail? 

https://github.com/oktadev/okta-blog/runs/4386062579?check_suite_focus=true

**Comment by bdemers** [comment]
🤔 We could probably add an exclude list, it's not ideal as it would likely exclude all of the linting, but that's probably not a big deal for cases like this (adding a post that targets another source/blog).

That said, if this is blocking you, we can roll back just the commit that enables the lining too: 303eceb6f973a8cbcc32f43931efa7d69846e966

**Comment by mraible** [comment]
It's not blocking me. We'll see if Auth0 recognizes the relative links when they load it up in their blog. ;)

**Pull request merged**
