### PR TITLE
Blog refresh - Main blog page and landing page

### PR DESCRIPTION
**Pull request by deepu105**
This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

### CODE REVIEW

**Review by havi — COMMENTED** [review]
The new styling of the home page and article pages looks super. 

I haven't inspected the source, but it looks like the author byline font size is now smaller than the font size of the article text, and it's too small for easy readability for me. Same with the read time. I would make the font size of the author name the same size as the tag font. And I would make the font size of the read time the size you're currently using for the byline. 

The author pages look great! Thanks.

**Comment by deepu105** [comment]
@havi thanks for taking a look, I was trying to implement as close to possible to the design. I'll play around with font size and weight to see if I can make it better

**Comment by mraible** [comment]
@deepu105 Is it possible to add a PDF of the design to this PR so we can compare the preview to what the design is? 

Some thoughts without looking at the design:

- The byline (author, date, and minutes to read) seems a little small compared to the large font we have now.
- I think the "minutes" in "10 mins read" should be singular, as in "10 min read" or "10 minute read".
- When looking at a single blog post, the author's avatar seems really small.
- I like the layout dev.to uses for title, byline, and tags. For example in [this post](https://dev.to/jhipster/how-to-deploy-jhipster-microservices-on-amazon-eks-using-terraform-and-kubernetes-49a5). We currently do date, title, author. This PR does tags, title, and author + date on the same line. dev.to does author + date, title, then tags.
- The tags' design look a little bold. Maybe that's the intent. I kinda like how dev.to makes them blend in a little.
- The tags links don't work. If tags are rendered on a post, there should be a tag page for them.
- There's a short line (maybe an `<hr/>`?) between the heading and the content that doesn't seem like it belongs.

**Comment by deepu105** [comment]
@mraible here is the design PDF. Not all elements are done, and I already made some minor changes from the design and yes agree that font is a bit smaller. I'll work on that and refine. thanks for the review.
[Blog Post Pge - Option 4.pdf](https://github.com/oktadev/okta-blog/files/9235847/Blog.Post.Pge.-.Option.4.pdf)

**Comment by deepu105** [comment]
@mraible @havi addressed most of your comments


- The byline (author, date, and minutes to read) seems a little small compared to the large font we have now.
  - Made them same size as body text
- I think the "minutes" in "10 mins read" should be singular, as in "10 min read" or "10 minute read".
  - fixed
- When looking at a single blog post, the author's avatar seems really small.
  - added 10px more to size
- I like the layout dev.to uses for title, byline, and tags. For example in [this post](https://dev.to/jhipster/how-to-deploy-jhipster-microservices-on-amazon-eks-using-terraform-and-kubernetes-49a5). We currently do date, title, author. This PR does tags, title, and author + date on the same line. dev.to does author + date, title, then tags.
  - That would be a complete departure from original design. Personally I find dev.to a bit congested
- The tags' design look a little bold. Maybe that's the intent. I kinda like how dev.to makes them blend in a little.
  - I have tried to make them subtle, let me know WYT?
- The tags links don't work. If tags are rendered on a post, there should be a tag page for them.
  - fixed
- There's a short line (maybe an `<hr/>`?) between the heading and the content that doesn't seem like it belongs.
  - It was in new design, if you think it doesn't add value we can remove it

**Comment by mraible** [comment]
I think we should remove the line since it adds unnecessary space, especially on mobile.

**Review by havi — APPROVED** [review]
Deepu, thanks for bumping the fonts up to where I can read them! :) 
Redesigned pages look great imo. 
Now I want a byline of my own... lol (I"ll have to work on that)

**Review by mraible — APPROVED** [review]

**Pull request merged**
