### PR TITLE
Update 2020-07-31-xamarin-essentials-webauthenticator.md

### PR DESCRIPTION
**Pull request by tommycwu**
The previous code has a lot of syntax errors and will not compile as is.

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadeveloper account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been ran through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

### CODE REVIEW

**Comment by mraible** [comment]
@tommycwu This post has a GitHub repo that needs to be updated too. Since it's a 2002 post, we might want to change it to use the CLI. See [these instructions](https://github.com/oktadeveloper/okta-blog#use-the-okta-cli-to-register-your-app) for more information.

@Quorralyne I noticed this post uses implicit flow, which we've tried to stay away from for the last year. Is it required for this post or can you switch it to authorization code flow?

**Comment by mraible** [comment]
I'm gonna close this issue if there's no action on it in the next few days.

**Comment by tommycwu** [comment]
Hi Sorry, slow to respond, yah, I think this article, like you said goes away since we have a sdk now.  Thanks.

**Comment by mraible** [comment]
@tommycwu Yes, it should be deprecated. However, we need a post that uses the new SDK to link to first.

**Comment by deepu105** [comment]
@mraible should we close this PR?

**Comment by mraible** [comment]
That's a good question for @tommycwu. Is this update still needed?

**Review by mraible — APPROVED** [review]

**Pull request merged**
