### PR TITLE
Add libvips installation to Dockerfile

### PR DESCRIPTION
**Pull request by tanay1337**
Currently, docker build fails with the following error:

```
=> ERROR [13/16] RUN npm install                                                              2.4s
------
 > [13/16] RUN npm install:
#17 0.322 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
#17 2.186
#17 2.186 > pre-push@0.1.1 install /app/node_modules/pre-push
#17 2.186 > node install.js
#17 2.186
#17 2.211
#17 2.211 > sharp@0.29.3 install /app/node_modules/sharp
#17 2.211 > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#17 2.211
#17 2.267 sharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.11.3
#17 2.267 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
#17 2.378 npm ERR! code ELIFECYCLE
#17 2.378 npm ERR! errno 1
#17 2.383 npm ERR! sharp@0.29.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
#17 2.383 npm ERR! Exit status 1
#17 2.383 npm ERR!
#17 2.383 npm ERR! Failed at the sharp@0.29.3 install script.
#17 2.383 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#17 2.388
#17 2.388 npm ERR! A complete log of this run can be found in:
#17 2.388 npm ERR!     /root/.npm/_logs/2022-01-03T12_44_03_551Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1

FAIL: 1
```

This PR updates the Dockerfile to install libvips 8.12.1.

### CODE REVIEW

**Comment by deepu105** [comment]
@tanay1337 I could not reproduce the issue on main branch, could you check again?

**Comment by tanay1337** [comment]
@deepu105 I still get the same error when running the following command:
`docker build . -t okta-blog`

**Comment by deepu105** [comment]
That's really strange maybe it only happens on your machine,  but still strange, I thought docker was supposed to be the solution for such issues.

Here is the sharp part I see in log when I run the command

```
Step 16/19 : RUN npm install
 ---> Running in 77f97caea8dd
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> pre-push@0.1.1 install /app/node_modules/pre-push
> node install.js


> sharp@0.29.3 install /app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
added 112 packages from 231 contributors and audited 112 packages in 27.014s

11 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 77f97caea8dd
 ---> 052a7648c481
```

**Comment by tanay1337** [comment]
This does not cause an issue for me anymore. Closing this PR for now.

**Pull request closed without merging**
