### PR TITLE
Replacing Disqus with discourse Okta Dev Forum

### PR DESCRIPTION
**Pull request by bdemers**
This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been ran through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

### CODE REVIEW

**Comment by bdemers** [comment]
It's working!
I added a test comment here:
https://deploy-preview-881--okta-blog.netlify.app/blog/2021/09/01/flask-scim-server#comments


The problem I had the whole time was the auto-generated topic's user was pre-populated to `devrel`, because that isn't a real user, the embedded comments broke in an odd way...

Anyway, it needs a bit of styling (controlled on the Discourse side).

**NOTE**: current this only works for this netlify preview domain

**Comment by mraible** [comment]
I'm not sure I'm ready to make the move from Disqus to Discourse. I've answered a lot of comments via Disqus and I'd hate to see those get lost. I think this needs a larger discussion between the team members.

**Comment by aaronpk** [comment]
@bdemers in order to preserve existing comments, I can import all the Disqus comments to Discourse threads. For all posts prior to the switchover, we'll need to add a new property in the yaml front matter to [map them to existing forum threads](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963#alternate-configuration-linking-to-existing-topics-6) using the `topicId` parameter instead of `discourseEmbedUrl`.

**Comment by bdemers** [comment]
Ahh, very cool! I take it all of the old posts would get the new frontmatter field, and then anything new would get generated?

**Comment by aaronpk** [comment]
Yep exactly! I'm almost done with a script to create forum topics for all the old posts, import the comments, then update the blog posts with the topic ID.

**Review by aaronpk — APPROVED** [review]

**Comment by bdemers** [comment]
🚢

**Pull request merged**
