### PR TITLE
Add post excerpt Liquid tag

### PR DESCRIPTION
**Pull request by alisaduncan**
Rendered output

image

Output when description doesn't exist

image

### CODE REVIEW

**Comment by alisaduncan** [comment]
iPhone SE

image

**Review by isemona — APPROVED** [review]
gtg!

**Review by edunham — APPROVED** [review]
🤩 so cool!

**Comment by alisaduncan** [comment]
Added Jekyll generated post excerpt as a fallback in cases the description doesn't exist

**Pull request merged**
