### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by aaronpk**
add an (invisible) link to our mastodon profile to verify the profile

### CODE REVIEW

**Review by alisaduncan — APPROVED** [review]
🦦

**Comment by deepu105** [comment]
You might have to update the field on the profile again to get it verified

**Comment by aaronpk** [comment]
what do you mean?

image

**Comment by deepu105** [comment]
Nvm, I had to force refresh to see it. When I did mine, * had to update again on Mastodon profile for green check to appear.

**Comment by aaronpk** [comment]
If you're on mastodon.social, it would take some time for it to be recognized since that poor server is super overloaded and it would be checking this verification in a low priority background task.

**Pull request merged**
