### PR TITLE
Add Applitools for visual testing of CLI include

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by colbyfayock** [comment]
@mraible looks like you have to update 

```
checkName: "Pages changed"
```

to

```
Pages changed - okta-blog
```

You might as well cancel that active workflow, i'm not sure if it will timeout but it's not finding the check

**Comment by colbyfayock** [comment]
i'm also not sure how it's going to handle the redirect from / to /blog, we'll see though

**Comment by colbyfayock** [comment]
in the meantime probably can cancel the CLI Setup :) that way it doesnt go on for 6 hours trying to ping the API. ill also set a default timeout for that retry to avoid that hanging like that

**Comment by mraible** [comment]
@colbyfayock I was thinking about this a bit yesterday. I think it'd be nice if this action could use Applitools to take a snapshot of what exists in the main branch. Then, it'd compare any incoming changes from PRs. It should also be smart enough to only be triggered if certain files change. Is that possible?

**Comment by colbyfayock** [comment]
yeah that first part is definitely my goal, being able to take advantage of the branching mechanism that Applitools has, the only challenge i need to figure out is how the "merge" happens of the differences between the Applitools branches

as far as the triggering on certain file changes, i would think that would be a simple thing to do. looks like you can do that with an Action configuration though:

https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/6

**Pull request closed without merging**
