### PR TITLE
Fixed duplicate user code to reflect SCIM spec

### PR DESCRIPTION
**Pull request by isemona**
This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist
- [ ] Images are compressed appropriately
- [ ] Social image previews well on Twitter and LinkedIn
- [ ] Tech review request (developer advocate or domain expert)
- [ ] Review request for editorial/grammar/clarity (developer advocate or Colton)

### CODE REVIEW

**Review by edunham — APPROVED** [review]
IMO it would be a good idea to add a couple sentences about it, or a comment to the code, because we've gone back and forth on this a few times and it's very unintuitive

**Review by alisaduncan — COMMENTED** [review]
Can we also remove some commented out console logs from this codeblock too?

**Comment by alisaduncan** [comment]
Reaching out to discuss change and uniqueness constraint

**Comment by isemona** [comment]
resolved in another PR

**Pull request closed without merging**
