### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by nicotriballier**
added 1 layer for the TOC, so it now displays #### titles

### CODE REVIEW

**Comment by mraible** [comment]
@nicotriballier Can you add a before and after screenshot so we can an example of how it looks?

**Comment by nicotriballier** [comment]
@mraible that's before
image
 vs after (i also rearranged some h2/h3/h4 titles that were improperly formatted)
image

**Comment by nicotriballier** [comment]
@mraible here we go u can see the 3 layers now for h2,h3,h4:
image

**Comment by mraible** [comment]
@nicotriballier I can merge this, but I'd also like to discourage you from using H4's. H2's are best for SEO and H3's don't even get processed (AFAIK). H4's just highlight that you have a really long post. ;)

**Review by mraible — APPROVED** [review]

**Comment by rdegges** [comment]
Heyo, we talked about this a bit. I don't think we should merge this.

There's nothing wrong with using H4's as far as I'm concerned, but I do think it ends up making a cluttered TOC. It makes sense to me that you'd want the TOC to have the h2s/h3s as those are the 'main sections' of the content, but if you're going deeper than that it ends up being pretty 'busy'.

If it were for a book or something, it'd make sense, for for a webpage I think it ends up being a bit distracting. My two cents.

@nicotriballier, thanks for the PR btw! Do you think you'd be OK with the TOC just showing the h2/h3s? When I look at the post with just those sections in the TOC it still looks nice/readable to me. What do ya think? <3

**Comment by nicotriballier** [comment]
Got it. I've used h4 in the blog content update, you can go ahead and
publish it. Not a big deal if you don't update the TOC, I don't know about
the impact on other blog posts, but I found it beneficial for the
https://developer.okta.com/blog/2020/04/06/configure-okta-asa-for-gcp-jenkins
post since it highlights the main steps to get it configured.

Thanks,

Nico

**Pull request closed without merging**
