### PR TITLE
Add screencast to Socket.IO + React post

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Review by deepu105 — APPROVED** [review]
LG

**Comment by mraible** [comment]
Doh! I should've made this a draft since I was planning to merge this tomorrow after the video is made public. 

No worries though, I think it's OK.

**Comment by deepu105** [comment]
Oops sorry :D

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I can revert it if you like

Thanks & Regards,
Deepu

**Comment by mraible** [comment]
No need. Thanks for being so on top of things!

**Pull request merged**
